language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements/compiled.txt --use-mirrors"

after_install:
  - git submodule update --init --recursive

script: ./manage.py test
