language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements/compiled.txt --use-mirrors"

before_script:
  - "mysql -e 'create database dashboard;'"
  - "git submodule update --init --recursive"
  - "mv settings_local.py-dist settings_local.py"

script: "./manage.py test"
