#!/bin/sh
curl -X DELETE 'http://localhost:9200/_all'
echo ""
echo "Everything is gone"
curl -X PUT 'http://localhost:9200/db'
echo ""
echo "new index created"
curl -X PUT 'http://localhost:9200/db/db/_mapping' -d '{
    "doc": {
        "properties": {
            "application_locale": {
                "type": "string",
                "index":"not_analyzed",
                "store":"yes"
            },
            "report_type": {
                "type": "string",
                "index":"not_analyzed",
                "store":"yes"
            }
        }
    }
}'

echo ""
echo "new mapping created"

echo ""
curl -XPUT 'http://localhost:9200/_river/db/_meta' -d '{
    "type" : "couchdb",
    "couchdb" : {
        "host" : "mozmill-release.brasstacks.mozilla.com",
        "port" : 80,
        "db" : "db",
        "filter" : null
    }
}'
echo ""
echo "Couchdb setup"
