#!/usr/bin/env python

import simplejson as json
import os
from httplib2 import Http
from multiprocessing import Pool

def turnaround(serial_number):
    h = Http()
    try:
        resp, content = h.request("http://mozmill-ci.blargon7.com/db/%s"%(serial_number), "GET")
        print content
        doc = json.loads(content)

        for (counter,function) in enumerate(doc['results']):
            if function['failed']==0:
                doc['results'][counter]['passed_function'] = function['name']
            else:
                doc['results'][counter]['failed_function'] = function['name']
            #doc['results'][counter]['name']
        post = json.dumps(doc)

        if resp['status']=='200':
            resp = h.request('http://localhost:8000/en-US/report/', "POST", post)
            print serial_number
        else:
            print content
    except Exception as e:
        print "exception: %s" % (serial_number)
        print e


def parse():
    f = open('_all_docs', 'r')
    doc_list = json.loads(f.read())
    #pool = Pool(processes=20)

    for row in doc_list['rows']:
        turnaround(row['id'])


if __name__=="__main__":
    parse()

